version: '2'

services:
  web:
    build: docker/web
    links:
      - mysql
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
  mysql:
    build: docker/mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "81:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
